//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorld.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "This feild is required")]
        public string UserName { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This feild is required")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }

        [Display(Name = "RePassword")]
        [Required(ErrorMessage = "This feild is required")]
        [DataType(DataType.Password)]
        [Compare("UserPassword", ErrorMessage = "Confirm password doesn't match, try again!")]
        public string ReUserPassword { get; set; }

    }
}
